### ISSUE TITLE
Corrupted Shapes

### ISSUE THREAD

**Issue by huanghoujing** [Jianningli/medshapenet-feedback#1]
Hi, @Jianningli, thank you for the sharing of the inspiring dataset!

I found these shapes corrupted:
- `005001_skull.stl`
- `009310_skull.stl`

Two indicators I found about corrupted files:
1. Very small file size, e.g. ~500 bytes.
2. `.stl` file content is truncated. E.g. with `endsolid` ending but without `solid` opening.

Reference: [STL (file format)](https://en.wikipedia.org/wiki/STL_(file_format)#ASCII)

**Comment by Jianningli** [comment]
> 

Hi @huanghoujing, thank you very much for reporting. We removed the corrupted files.

**Comment by Jianningli** [comment]
> Hi, @Jianningli, thank you for the sharing of the inspiring dataset!
> 
> I found these shapes corrupted:
> 
> * `005001_skull.stl`
> * `009310_skull.stl`
> 
> Two indicators I found about corrupted files:
> 
> 1. Very small file size, e.g. ~500 bytes.
> 2. `.stl` file content is truncated. E.g. with `endsolid` ending but without `solid` opening.
> 
> Reference: [STL (file format)](https://en.wikipedia.org/wiki/STL_(file_format)#ASCII)

Hi @huanghoujing, thank you very much for reporting. We removed the corrupted files.
