### ISSUE TITLE
data_skull.py is missing

### ISSUE THREAD

**Issue by makarovNick** [Jianningli/medshapenet-feedback#5]
Hello! Great work!
However, I cannot try out Skull shape completion due to absence of data_skull.py.
It would be great if you can provide source file.
Thanks

**Comment by Jianningli** [comment]
Hi,
Thanks for your interest. You can find it here: 

https://github.com/akroviakov/SparseSkullCompletion
https://link.springer.com/chapter/10.1007/978-3-030-92652-6_7

**Comment by Jianningli** [comment]
> Hello! Great work! However, I cannot try out Skull shape completion due to absence of data_skull.py. It would be great if you can provide source file. Thanks

Hi,
Thanks for your interest. You can find it here:

https://github.com/akroviakov/SparseSkullCompletion
https://link.springer.com/chapter/10.1007/978-3-030-92652-6_7
